Readerself\CoreBundle\Entity\Member:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        email:
            - NotBlank: ~
            - Email: ~
        plainPassword:
            - NotBlank: { groups: [insert] }
            - Type: string
            - Length:
                min: 6

Readerself\CoreBundle\Entity\Login:
    properties:
        email:
            - NotBlank: ~
        plainPassword:
            - NotBlank: ~

Readerself\CoreBundle\Entity\Feed:
    properties:
        title:
            - NotBlank: ~
        link:
            - NotBlank: ~
