security:
    encoders:
        Readerself\CoreBundle\Entity\Member:
            algorithm: "bcrypt"

    providers:
        readerself_core_provider:
            entity:
                class: Readerself\CoreBundle\Entity\Member
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            stateless: true
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
