Readerself\CoreBundle\Entity\ActionItem:
    type: entity
    table: action_item
    indexes:
        IDX_69FA9E10126F525E:
            columns:
                - item_id
        IDX_69FA9E109D32F035:
            columns:
                - action_id
    uniqueConstraints:
        action_id_item_id:
            columns:
                - action_id
                - item_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        item:
            targetEntity: Item
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                item_id:
                    nullable: false
                    referencedColumnName: id
            orphanRemoval: false
        action:
            targetEntity: Action
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                action_id:
                    nullable: false
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
