Readerself\CoreBundle\Entity\ActionItemMember:
    type: entity
    table: action_item_member
    indexes:
        item_id:
            columns:
                - item_id
        member_id:
            columns:
                - member_id
        action_id:
            columns:
                - action_id
    uniqueConstraints:
        action_id_item_id_member_id:
            columns:
                - action_id
                - item_id
                - member_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
    manyToOne:
        item:
            targetEntity: Item
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                item_id:
                    nullable: false
                    referencedColumnName: id
                    onDelete: "cascade"
            orphanRemoval: false
        member:
            targetEntity: Member
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                member_id:
                    nullable: false
                    referencedColumnName: id
                    onDelete: "cascade"
            orphanRemoval: false
        action:
            targetEntity: Action
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                action_id:
                    nullable: false
                    referencedColumnName: id
                    onDelete: "cascade"
            orphanRemoval: false
    lifecycleCallbacks: {  }
