Readerself\CoreBundle\Entity\Collection:
    type: entity
    table: collection
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        feeds:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        errors:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        time:
            type: float
            nullable: false
            precision: 10
            scale: 0
        memory:
            type: integer
            nullable: false
            options:
                unsigned: true
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
    lifecycleCallbacks: {  }
