Readerself\CoreBundle\Entity\Feed:
    repositoryClass: Readerself\CoreBundle\Repository\FeedRepository
    type: entity
    table: feed
    indexes:
        next_collection:
            columns:
                - next_collection
    uniqueConstraints:
        link:
            columns:
                - link
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        link:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        website:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        hostname:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        language:
            type: string
            nullable: true
            length: 2
            options:
                fixed: true
        direction:
            type: string
            nullable: true
            length: 3
            options:
                fixed: true
        nextCollection:
            type: datetime
            nullable: true
            column: next_collection
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        dateModified:
            type: datetime
            nullable: false
            column: date_modified
    lifecycleCallbacks: {  }
