Readerself\CoreBundle\Entity\Folder:
    repositoryClass: Readerself\CoreBundle\Repository\FolderRepository
    type: entity
    table: folder
    indexes:
        member_id:
            columns:
                - member_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        direction:
            type: string
            nullable: true
            length: 3
            options:
                fixed: true
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
    manyToOne:
        member:
            targetEntity: Member
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                member_id:
                    nullable: false
                    referencedColumnName: id
                    onDelete: "cascade"
            orphanRemoval: false
    lifecycleCallbacks: {  }
