Readerself\CoreBundle\Entity\Item:
    repositoryClass: Readerself\CoreBundle\Repository\ItemRepository
    type: entity
    table: item
    indexes:
        feed_id:
            columns:
                - feed_id
        author_id:
            columns:
                - author_id
        date:
            columns:
                - date
    uniqueConstraints:
        link:
            columns:
                - link
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        link:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        date:
            type: datetime
            nullable: false
        content:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        contentFull:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: content_full
        latitude:
            type: float
            nullable: true
            precision: 10
            scale: 0
        longitude:
            type: float
            nullable: true
            precision: 10
            scale: 0
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        dateModified:
            type: datetime
            nullable: false
            column: date_modified
    manyToOne:
        feed:
            targetEntity: Feed
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                feed_id:
                    nullable: false
                    referencedColumnName: id
                    onDelete: "cascade"
            orphanRemoval: false
        author:
            targetEntity: Author
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                author_id:
                    referencedColumnName: id
                    onDelete: "set null"
            orphanRemoval: false
    oneToMany:
        enclosures:
            targetEntity: Enclosure
            mappedBy: item
    lifecycleCallbacks: {  }
