Readerself\CoreBundle\Entity\Push:
    repositoryClass: Readerself\CoreBundle\Repository\PushRepository
    type: entity
    table: push
    indexes:
        member_id:
            columns:
                - member_id
    uniqueConstraints:
        endpoint:
            columns:
                - endpoint
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        endpoint:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        publicKey:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: public_key
        authenticationSecret:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: authentication_secret
        ip:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        agent:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        dateModified:
            type: datetime
            nullable: false
            column: date_modified
    manyToOne:
        member:
            targetEntity: Member
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                member_id:
                    nullable: false
                    referencedColumnName: id
                    onDelete: "cascade"
            orphanRemoval: false
    lifecycleCallbacks: {  }
