Readerself\CoreBundle\Entity\Subscription:
    type: entity
    table: subscription
    indexes:
        member_id:
            columns:
                - member_id
        feed_id:
            columns:
                - feed_id
        folder_id:
            columns:
                - folder_id
    uniqueConstraints:
        member_id_feed_id:
            columns:
                - member_id
                - feed_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        priority:
            type: boolean
            nullable: false
            options:
                default: '0'
        direction:
            type: string
            nullable: true
            length: 3
            options:
                fixed: true
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
    manyToOne:
        folder:
            targetEntity: Folder
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                folder_id:
                    referencedColumnName: id
                    onDelete: "set null"
            orphanRemoval: false
        feed:
            targetEntity: Feed
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                feed_id:
                    nullable: false
                    referencedColumnName: id
                    onDelete: "cascade"
            orphanRemoval: false
        member:
            targetEntity: Member
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                member_id:
                    nullable: false
                    referencedColumnName: id
                    onDelete: "cascade"
            orphanRemoval: false
    lifecycleCallbacks: {  }
