#crud
readerself_api_member_create:
    path: /member
    defaults:
        _controller: "readerself_core_controller_member:createAction"
    methods: POST

readerself_api_member_read:
    path: /member/{id}
    defaults:
        _controller: "readerself_core_controller_member:readAction"
    requirements:
        id: '\d+'
    methods: GET

readerself_api_member_update:
    path: /member/{id}
    defaults:
        _controller: "readerself_core_controller_member:updateAction"
    requirements:
        id: '\d+'
    methods: PUT

readerself_api_member_delete:
    path: /member/{id}
    defaults:
        _controller: "readerself_core_controller_member:deleteAction"
    requirements:
        id: '\d+'
    methods: DELETE

readerself_api_member_login:
    path: /login
    defaults:
        _controller: "readerself_core_controller_member:loginAction"
    methods: POST

readerself_api_member_profile:
    path: /profile
    defaults:
        _controller: "readerself_core_controller_member:profileAction"
    methods: GET

readerself_api_member_profile_update:
    path: /profile/update
    defaults:
        _controller: "readerself_core_controller_member:profileUpdateAction"
    methods: PUT

readerself_api_member_logout:
    path: /logout
    defaults:
        _controller: "readerself_core_controller_member:logoutAction"
    methods: GET

readerself_api_member_pinboard:
    path: /pinboard
    defaults:
        _controller: "readerself_core_controller_member:pinboardAction"
    methods: POST
