Axipi\FeedBundle\Entity\Push:
    type: entity
    table: push
    indexes:
        IDX_13E501FFA76ED395:
            columns:
                - member_id
    uniqueConstraints:
        UNIQ_13E501FFC4420F7B:
            columns:
                - endpoint
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        endpoint:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        publickey:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: publicKey
        authenticationsecret:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: authenticationSecret
        agent:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        dateModified:
            type: datetime
            nullable: false
            column: date_modified
    manyToOne:
        member:
            targetEntity: Member
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                member_id:
                    nullable: false
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
